fix tf injection

diff --git a/.github/workflows/update_ecs_task_definitions.yml b/.github/workflows/update_ecs_task_definitions.yml
--- a/.github/workflows/update_ecs_task_definitions.yml
+++ b/.github/workflows/update_ecs_task_definitions.yml
@@ -36,6 +36,47 @@ jobs:
           role-session-name: GitHub_to_AWS_via_FederatedOIDC
           aws-region: ${{ env.AWS_DEFAULT_REGION }}
 
+      - name: Install jq
+        run: sudo apt-get install -y jq
+
+      - name: List and filter ECS task definitions
+        run: |
+          #!/bin/bash
+
+          set -e  # Exit immediately if a command exits with a non-zero status
+
+          # List of keywords to filter task definitions
+          KEYWORDS=("ecs-fargate-trend-demo-nginx" "trendmicro-scout")
+
+          # List all ECS task definitions
+          echo "Listing all ECS task definitions..."
+          TASK_DEFINITIONS=$(aws ecs list-task-definitions)
+
+          # Check if the command was successful
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to list ECS task definitions"
+            exit 1
+          fi
+
+          # Display the raw JSON output
+          echo "Raw JSON output:"
+          echo $TASK_DEFINITIONS
+
+          # Pretty print the JSON output using jq
+          echo "Pretty printed JSON output:"
+          echo $TASK_DEFINITIONS | jq .
+
+          # Filter task definitions based on keywords
+          echo "Filtering task definitions..."
+          FILTERED_TASK_DEFINITIONS=$(echo $TASK_DEFINITIONS | jq -r --argjson keywords "$(printf '%s\n' "${KEYWORDS[@]}" | jq -R . | jq -s .)" '.taskDefinitionArns[] | select(. as $arn | $keywords | any(. as $keyword | $arn | contains($keyword)))')
+
+          # Display the filtered task definitions
+          echo "Filtered task definitions:"
+          echo $FILTERED_TASK_DEFINITIONS
+
+          # Save filtered task definitions to a file
+          echo $FILTERED_TASK_DEFINITIONS > desired_task_definitions.txt
+
       - name: Check for required files
         run: |
           if [ ! -f ./desired_task_definitions.txt ]; then
